baseURL = "https://www.13log.live/"
title = "13log"
# 若用 Submodule 安装主题：
theme = "hugo-PaperMod"

enableRobotsTXT = true
enableEmoji = true

[outputs]
  home = ["HTML", "RSS", "JSON"]          # PaperMod 搜索需要 JSON

[pagination]
  pagerSize = 30                           # 新版键名（替代 paginate）
                                           # Hugo 0.128+ 要用这个键

[params]
  browserTitle = "我的小小世界"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowToc = true
  ShowCodeCopyButtons = true
  readingTime = 300  # 每分钟300字（中文标准）

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params.assets]
  favicon = "/favicon-32x32.png"
  favicon16x16 = "/favicon-16x16.png"
  favicon32x32 = "/favicon-32x32.png"
  apple_touch_icon = "/apple-touch-icon.png"
  safari_pinned_tab = "/safari-pinned-tab.svg"
  theme_color = "#2e2e33"
  msapplication_TileColor = "#2e2e33"

[params.profileMode]
  enabled = true
  title = "花似伊，柳似伊"
  imageUrl = "/images/avatar.jpg"
  imageTitle = "Avatar"
  subtitle = "Coding • Books • Life"

  [[params.profileMode.buttons]]
  name = "Posts"
  url  = "/posts/"

  [[params.profileMode.buttons]]
  name = "Coding"
  url  = "/coding/"

  # [[params.profileMode.buttons]]
  # name = "Archive"
  # url  = "/archives/"

  [[params.profileMode.buttons]]
  name = "About"
  url  = "/about/"

  [[params.profileMode.buttons]]
  name = "Photos"
  url  = "/photos/"

  [[params.profileMode.buttons]]
  name = "Link"
  url  = "/link/"
